export PATH="$PATH:$HOME/.local/bin"
export GO="/usr/local/go"
export PATH="$PATH:$GO/bin"
export GO_HOME="$HOME/go"
export PATH="$PATH:$GO_HOME/bin"
export PATH="$PATH:$HOME/scripts"
export TERMINAL="alacritty"
export EDITOR="nvim"
