# Changing prefix to Ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Increasing the history limit buffer
set-option -g history-limit 5000

# Start numbering at 1
set -g base-index 1

# vim like pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Toggle through panes without needing to invoke the prefix using Alt + arrow keys
bind -n m-Left select-pane -L
bind -n m-Right select-pane -R
bind -n m-Up select-pane -U
bind -n m-Down select-pane -D

# open new pane/window in current path
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Copy tmux buffer to system clipboard and use vim keybindings
set-option -g mouse on
setw -g mode-key vi
set-option -s set-clipboard off
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'pbcopy' \; display-message "Copied to Clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy' \; display-message "Copied to Clipboard"

# Move panes across windows
bind-key g command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key m command-prompt -p "send pane to:"  "join-pane -t '%%'"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Theme plugin
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark' # or 'light'

set -g @plugin 'catppuccin/tmux#v2.1.0'

# set -g @plugin 'z3z1ma/tmux-gruvbox'

# reload config file
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
