#!/bin/bash

idx="$1"
name="$2"

space=$(yabai -m query --spaces --space "$idx")

# if space doesn't exist with the index
if [ -z space ]; then
  yabai -m space --create
fi

# assign the label
yabai -m space "$idx" --label "$name"
